<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQr32lEx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQr32lEx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQr32lEx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQr32lEx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQr32lEx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Qr32lEx',
    'container.build_id' => '722c0508',
    'container.build_time' => 1678920311,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQr32lEx');
